{
 "title": "Wordle",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Overall Average",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(score) FROM score LIMIT 50 "
    }
   ]
  },
  {
   "title": "7 Day Overall Average",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(score) FROM score WHERE date >= now() - interval '7 days'"
    }
   ]
  },
  {
   "title": "Overall Averages",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(score), username FROM score GROUP BY username ORDER BY AVG(score) LIMIT 50 "
    }
   ]
  },
  {
   "title": "7 Day Average",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT AVG(score), username FROM score WHERE date >= now() - interval '7 days' GROUP BY username ORDER BY AVG(score) LIMIT 50 "
    }
   ]
  },
  {
   "title": "Averages Over Time",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT Date, username, AVG(Score) OVER (PARTITION BY username ORDER BY Date) AS average_score\r\nFROM Score\r\nORDER BY Date;"
    }
   ]
  },
  {
   "title": "7 day averages",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT Date, username, AVG(Score) OVER (PARTITION BY username ORDER BY Date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS average_7day\r\nFROM Score\r\nORDER BY Date;"
    }
   ]
  },
  {
   "title": "Month Averages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    DATE_TRUNC('month', date) + INTERVAL '4 Hours' AS month,\r\n    username,\r\n    AVG(score) AS average_score\r\nFROM\r\n    public.score\r\nGROUP BY\r\n    month,\r\n    username\r\nORDER BY\r\n    month;"
    }
   ]
  },
  {
   "title": "Overall average ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT Date, AVG(Score) OVER (ORDER BY Date) AS average_score\r\nFROM Score\r\nORDER BY Date;"
    }
   ]
  },
  {
   "title": "Scores",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT Date, username, Score\r\nFROM Score\r\nORDER BY Date;"
    }
   ]
  }
 ]
}